version: '3'
services:
  app:
    container_name: api_gateway
    image: node:10-alpine
    restart: always
    command: sh -c "npm install && npm run start"
    working_dir: /var/www/myapp
    volumes:
      - ".:/var/www/myapp"
    ports:
      - "${API_PORT}:${API_PORT}"